<?php

namespace App\Console\Commands;

use App\Models\Course;
use App\Models\User;
use Illuminate\Console\Command;
use Illuminate\Support\Str;

class ExportTableSeeder extends Command
{
    protected $signature = 'seed:export {table : courses or students}
                            {--output= : Output file path, defaults to database/seeders/<Table>SnapshotSeeder.php}';

    protected $description = 'Generate a seeder file from the courses or students rows currently in the database.';

    public function handle(): int
    {
        $table = strtolower($this->argument('table'));

        return match ($table) {
            'courses', 'course' => $this->exportCourses(),
            'students', 'student' => $this->exportStudents(),
            default => $this->failWith("Unknown table \"$table\" — expected \"courses\" or \"students\"."),
        };
    }

    private function failWith(string $message): int
    {
        $this->error($message);
        return self::FAILURE;
    }

    private function exportCourses(): int
    {
        $courses = Course::all();

        if ($courses->isEmpty()) {
            $this->info('No courses found — nothing to export.');
            return self::SUCCESS;
        }

        $rows = $courses->map(function (Course $course) {
            return [
                'title' => $course->title,
                'description' => $course->description,
                'category' => $course->category,
                'icon_name' => $course->icon_name,
                'duration' => $course->duration,
                'price' => $course->price,
                'price_min' => $course->price_min,
                'price_max' => $course->price_max,
                'tools_count' => $course->tools_count,
                'features' => $course->features,
                'certificate_config' => $course->certificate_config,
            ];
        })->all();

        $this->writeSeeder('CourseSnapshotSeeder', 'Course', $rows, $courses->count());

        return self::SUCCESS;
    }

    private function exportStudents(): int
    {
        $students = User::where('role', 'student')->get();

        if ($students->isEmpty()) {
            $this->info('No students found — nothing to export.');
            return self::SUCCESS;
        }

        $this->warn('Heads up: this bakes real student names/emails/password hashes into a PHP file. Think twice before committing it to git — see the comment at the top of the generated file.');

        $rows = $students->map(function (User $user) {
            return [
                'name' => $user->name,
                'email' => $user->email,
                'password' => $user->password, // already hashed — not reversible to plaintext
                'role' => $user->role,
                'theme' => $user->theme,
                'email_verified_at' => $user->email_verified_at?->toIso8601String(),
            ];
        })->all();

        $this->writeSeeder('StudentSnapshotSeeder', 'User', $rows, $students->count());

        return self::SUCCESS;
    }

    private function writeSeeder(string $className, string $modelClass, array $rows, int $count): void
    {
        $outputPath = $this->option('output') ?: database_path("seeders/{$className}.php");

        $exported = var_export($rows, true);
        // var_export emits "array (" / NULL / TRUE / FALSE — normalize to match project style.
        $exported = preg_replace('/array \(/', '[', $exported);
        $exported = preg_replace('/\)(,?)$/m', ']$1', $exported);
        $exported = preg_replace('/\bNULL\b/', 'null', $exported);
        $exported = preg_replace('/\bTRUE\b/', 'true', $exported);
        $exported = preg_replace('/\bFALSE\b/', 'false', $exported);

        $isStudent = $className === 'StudentSnapshotSeeder';
        $piiNotice = $isStudent
            ? "\n * ⚠️  Contains real student names/emails/password hashes captured at generation time.\n * Think before committing this to git — it's a permanent, plaintext-searchable record\n * of real user data in version control history. Consider whether it belongs in .gitignore\n * instead, or whether the emails should be anonymized first.\n *"
            : '';

        $content = <<<PHP
<?php

namespace Database\Seeders;

use App\Models\\{$modelClass};
use Illuminate\Database\Seeder;

/**
 * Auto-generated by `php artisan seed:export {$this->argument('table')}` on {$this->now()}.
 * Snapshot of the {$count} row(s) present in the database at generation time — running
 * this again will regenerate it from whatever's in the database *then*, not update this file.{$piiNotice}
 */
class {$className} extends Seeder
{
    public function run(): void
    {
        \$rows = {$exported};

        foreach (\$rows as \$row) {
            {$modelClass}::updateOrCreate(
                ['email' => \$row['email'] ?? null] ?: ['title' => \$row['title'] ?? null],
                \$row
            );
        }
    }
}

PHP;

        // Course rows have no 'email' key — key the upsert on 'title' instead for those.
        if ($modelClass === 'Course') {
            $content = str_replace(
                "['email' => \$row['email'] ?? null] ?: ['title' => \$row['title'] ?? null],",
                "['title' => \$row['title']],",
                $content
            );
        } else {
            $content = str_replace(
                "['email' => \$row['email'] ?? null] ?: ['title' => \$row['title'] ?? null],",
                "['email' => \$row['email']],",
                $content
            );
        }

        file_put_contents($outputPath, $content);

        $this->info("Wrote {$count} row(s) to {$outputPath}");
    }

    private function now(): string
    {
        return now()->toDateTimeString();
    }
}
