<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            // Marketing
            [
                'title' => 'Digital Marketing',
                'category' => 'Marketing',
                'icon_name' => 'Rocket',
                'description' => 'Learn how to promote businesses online using SEO, social media, ads, and content marketing. This course focuses on practical strategies and real-world marketing tools to make your job-ready.',
                'price_min' => 99,
                'price_max' => 499,
                'features' => ['Practical Strategies', 'Real-world Tools', 'Job-Ready Focus'],
                'duration' => '8 Weeks',
            ],
            [
                'title' => 'Search Engine Optimization (SEO)',
                'category' => 'Marketing',
                'icon_name' => 'Search',
                'description' => 'Learn how to rank websites on Google using keyword research, on-page and technical SEO, and content strategies that drive consistent organic traffic and long-term online visibility.',
                'price_min' => 300,
                'price_max' => 1200,
                'features' => ['Keyword Research', 'Technical SEO', 'Organic Traffic'],
                'duration' => '8 Weeks',
            ],
            [
                'title' => 'Social Media Marketing',
                'category' => 'Marketing',
                'icon_name' => 'Users',
                'description' => 'Master social media growth with content planning, organic strategies, and high-performing ad campaigns that build brand awareness, increase engagement, and deliver measurable business results.',
                'price_min' => 300,
                'price_max' => 1200,
                'features' => ['Content Planning', 'Ad Campaigns', 'Brand Awareness'],
                'duration' => '8 Weeks',
            ],
            [
                'title' => 'Email Marketing',
                'category' => 'Marketing',
                'icon_name' => 'Mail',
                'description' => 'Understand end-to-end email marketing, from audience targeting and content creation to automation and analytics, to generate quality leads, boost engagement, and increase repeat sales.',
                'price_min' => 300,
                'price_max' => 1000,
                'features' => ['Audience Targeting', 'Automation', 'Analytics'],
                'duration' => '8 Weeks',
            ],
            // Development
            [
                'title' => 'Website Development',
                'category' => 'Development',
                'icon_name' => 'Code',
                'description' => 'Gain a strong foundation in building modern, responsive, and user-friendly websites. This course covers core web technologies and hands-on project work to prepare learners for real-world development roles.',
                'price_min' => 2000,
                'price_max' => 5000,
                'features' => ['Modern Frameworks', 'Responsive Design', 'Real-world Projects'],
                'duration' => '10 Weeks',
            ],
            // Design
            [
                'title' => 'Graphic Design',
                'category' => 'Design',
                'icon_name' => 'Image',
                'description' => 'Develop professional creative and visual communication skills for digital and print media. Learn industry-standard design tools and techniques used in branding, marketing, and digital platforms.',
                'price_min' => 1500,
                'price_max' => 4000,
                'features' => ['Creative Branding', 'Digital Tools', 'Visual Communication'],
                'duration' => '8 Weeks',
            ],
            [
                'title' => 'UI/UX Design',
                'category' => 'Design',
                'icon_name' => 'Palette',
                'description' => 'Learn to design intuitive, user-centric digital experiences. The course focuses on user research, wireframing, prototyping, and modern UI tools to design effective websites and applications.',
                'price_min' => 500,
                'price_max' => 2000,
                'features' => ['User Research', 'Prototyping', 'Modern UI Tools'],
                'duration' => '8 Weeks',
            ],
            // Strategy
            [
                'title' => 'Product Management',
                'category' => 'Strategy',
                'icon_name' => 'LayoutDashboard',
                'description' => 'Build the skills required to plan, develop, and manage successful digital products. This course emphasizes product strategy, user needs, business objectives, and real-world case studies from the industry.',
                'price_min' => 2000,
                'price_max' => 5000,
                'features' => ['Product Strategy', 'Business Objectives', 'Case Studies'],
                'duration' => '8 Weeks',
            ],
            // Data
            [
                'title' => 'Basic Excel Course',
                'category' => 'Data',
                'icon_name' => 'BarChart3',
                'description' => 'Learn Excel essentials, including worksheets, formulas, formatting, and data organization, to confidently handle spreadsheets and build a solid foundation for beginners.',
                'price_min' => 100,
                'price_max' => 500,
                'features' => ['Worksheets', 'Formulas', 'Data Organization'],
                'duration' => '4 Weeks',
            ],
            [
                'title' => 'Advanced Excel Course',
                'category' => 'Data',
                'icon_name' => 'BarChart3',
                'description' => 'Enhance your Excel expertise with advanced formulas, pivot tables, dashboards, and professional reports to analyze data efficiently and make smarter business decisions.',
                'price_min' => 300,
                'price_max' => 1000,
                'features' => ['Pivot Tables', 'Dashboards', 'Data Analysis'],
                'duration' => '6 Weeks',
            ],
            [
                'title' => 'Data Analysis with Excel',
                'category' => 'Data',
                'icon_name' => 'BarChart3',
                'description' => 'Learn Excel data analysis, explore formulas, pivot tables, and charts to uncover insights, create meaningful reports, and support data-driven business decisions confidently.',
                'price_min' => 300,
                'price_max' => 1200,
                'features' => ['Insight Uncovering', 'Meaningful Reports', 'Data Decisions'],
                'duration' => '6 Weeks',
            ],
            [
                'title' => 'Data Visualization with Excel',
                'category' => 'Data',
                'icon_name' => 'MonitorPlay',
                'description' => 'Master Excel visualization by creating interactive charts and dashboards that simplify complex data into clear, engaging, and professional visual reports for business use.',
                'price_min' => 800,
                'price_max' => 2000,
                'features' => ['Interactive Charts', 'Visual Reports', 'Complex Data'],
                'duration' => '6 Weeks',
            ],
            [
                'title' => 'Automation VBA & Macros',
                'category' => 'Data',
                'icon_name' => 'Zap',
                'description' => 'Streamline Excel works by learning VBA programming and macros to automate repetitive tasks, improve efficiency, and handle complex processes with ease and accuracy.',
                'price_min' => 800,
                'price_max' => 2500,
                'features' => ['VBA Programming', 'Macros', 'Task Automation'],
                'duration' => '8 Weeks',
            ],
            // AI
            [
                'title' => 'Intro to Artificial Intelligence',
                'category' => 'AI',
                'icon_name' => 'Bot',
                'description' => 'Discover AI fundamentals, understand real-world applications, and explore how artificial intelligence shapes industries while building a strong knowledge base for students.',
                'price_min' => 800,
                'price_max' => 2500,
                'features' => ['AI Fundamentals', 'Industry Impact', 'Strong Knowledge Base'],
                'duration' => '6 Weeks',
            ],
            [
                'title' => 'AI for Business Analytics',
                'category' => 'AI',
                'icon_name' => 'Brain',
                'description' => 'Learn to use AI for analyzing trends, making data-driven decisions, and understanding business insights, giving students practical skills for analytics without coding.',
                'price_min' => 1000,
                'price_max' => 3500,
                'features' => ['Trend Analysis', 'Non-Coding Analytics', 'Business Insights'],
                'duration' => '8 Weeks',
            ],
            [
                'title' => 'AI & Chatbot Development',
                'category' => 'AI',
                'icon_name' => 'MessageSquare',
                'description' => 'Create AI chatbots and automated interactions, enhancing students\' understanding of practical AI applications and improving problem-solving and communication skills.',
                'price_min' => 1500,
                'price_max' => 4000,
                'features' => ['Chatbot Creation', 'Automated Interaction', 'Problem Solving'],
                'duration' => '8 Weeks',
            ],
            [
                'title' => 'RPA with AI',
                'category' => 'AI',
                'icon_name' => 'Workflow',
                'description' => 'Streamline repetitive tasks using AI automation tools, helping students boost efficiency, manage workflows, and gain practical skills for everyday business tasks.',
                'price_min' => 1500,
                'price_max' => 4000,
                'features' => ['Efficiency Boost', 'Workflow Management', 'Automation Tools'],
                'duration' => '8 Weeks',
            ],
            [
                'title' => 'Generative AI for Content',
                'category' => 'AI',
                'icon_name' => 'Sparkles',
                'description' => 'Explore AI tools to generate text, images, and multimedia content, teaching students creative applications of AI and improving their digital content skills.',
                'price_min' => 1000,
                'price_max' => 3000,
                'features' => ['Creative AI', 'Multimedia Generation', 'Digital Content'],
                'duration' => '6 Weeks',
            ],
            [
                'title' => 'AI in Data Visualization',
                'category' => 'AI',
                'icon_name' => 'PieChart',
                'description' => 'Transform data into interactive dashboards and AI-powered visual reports, enabling students to communicate insights clearly without writing a single line of code.',
                'price_min' => 1000,
                'price_max' => 3000,
                'features' => ['AI-Powered Reports', 'Interactive Dashboards', 'No-Code Insights'],
                'duration' => '6 Weeks',
            ],
            [
                'title' => 'AI for Office Productivity',
                'category' => 'AI',
                'icon_name' => 'Briefcase',
                'description' => 'Use AI tools in Excel, Word, and PowerPoint to automate tasks, create smart documents, and increase efficiency, helping students become tech-savvy professionals.',
                'price_min' => 800,
                'price_max' => 2500,
                'features' => ['Office Automation', 'Smart Documents', 'Professional Efficiency'],
                'duration' => '6 Weeks',
            ],
            [
                'title' => 'AI in Marketing & Sales',
                'category' => 'AI',
                'icon_name' => 'TrendingUp',
                'description' => 'Explore AI tools to learn marketing and sales strategies, analyze trends, and understand customer behavior, helping students gain practical, non-coding skills for success.',
                'price_min' => 1000,
                'price_max' => 3500,
                'features' => ['Marketing AI', 'Customer Behavior', 'Trend Analysis'],
                'duration' => '8 Weeks',
            ],
            [
                'title' => 'AI Tools for Professionals',
                'category' => 'AI',
                'icon_name' => 'Laptop',
                'description' => 'Gain hands-on experience with ChatGPT, DALL·E, and other AI tools, enhancing creativity, problem-solving, and workflow management skills without coding knowledge.',
                'price_min' => 800,
                'price_max' => 2500,
                'features' => ['ChatGPT & DALL·E', 'Workflow Management', 'Hands-on Experience'],
                'duration' => '6 Weeks',
            ],
            [
                'title' => 'AI Ethics & Applications',
                'category' => 'AI',
                'icon_name' => 'ShieldCheck',
                'description' => 'Learn responsible AI use, study real-world examples, and develop critical thinking to make ethical decisions while applying AI concepts in various professional scenarios.',
                'price_min' => 1000,
                'price_max' => 3500,
                'features' => ['Responsible AI', 'Ethical Decisions', 'Critical Thinking'],
                'duration' => '6 Weeks',
            ],
        ];

        foreach ($courses as $course) {
            Course::create($course);
        }
    }
}